/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ethanco_jni_JniTest */

#ifndef _Included_com_ethanco_jni_JniTest
#define _Included_com_ethanco_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ethanco_jni_JniTest_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    getStringFromC2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ethanco_jni_JniTest_getStringFromC2
  (JNIEnv *, jobject);

/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ethanco_jni_JniTest_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ethanco_jni_JniTest_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ethanco_jni_JniTest_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ethanco_jni_JniTest_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    accessConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_ethanco_jni_JniTest_accessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    accessNonvirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ethanco_jni_JniTest_accessNonvirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_ethanco_jni_JniTest
 * Method:    chineseChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ethanco_jni_JniTest_chineseChars
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
